# Generated by Django 2.2.6 on 2020-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.AutoField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
