# Generated by Django 3.1.2 on 2020-10-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20201007_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='PollsResults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Questions', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='questionanswerpair',
            name='poll_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='QuestionAnswerPairs', to='polls.pollresult'),
        ),
    ]
