# Generated by Django 3.1.2 on 2020-10-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201010_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.AlterField(
            model_name='questionanswerpair',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.possibleanswer'),
        ),
    ]
