# Generated by Django 3.1.2 on 2020-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201010_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('st', 'smalltext'), ('bt', 'bigtext'), ('r', 'radio'), ('c', 'checkbox')], default='c', max_length=10),
            preserve_default=False,
        ),
    ]
