# Generated by Django 3.1.2 on 2020-10-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.SlugField(default='default_slug', max_length=32),
            preserve_default=False,
        ),
    ]
