# Generated by Django 3.1.2 on 2020-10-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
