# Generated by Django 3.1.2 on 2020-12-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201212_1324'),
        ('polls', '0009_auto_20201021_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.team'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('st', 'smalltext'), ('bt', 'bigtext'), ('r', 'radio'), ('c', 'checkbox')], default='smalltext', max_length=10),
        ),
    ]
